# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches: ["challenge-8"]
  pull_request:
    branches: ["challenge-8"]
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
